# This is a basic workflow to help you get started with Actions

name: Deploy Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2.0.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: 'b1g34n0j9lktsmu9ijjf'
          function-name: 'telegram-hanabigame-bot'
          runtime: 'python39'
          memory: '128Mb'
          entrypoint: 'index.handler'
          include: |
            .
          exclude: |
            .github
